// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/blazee5/cloud-drive/files/ent/file"
	"github.com/blazee5/cloud-drive/files/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescDownloadCount is the schema descriptor for download_count field.
	fileDescDownloadCount := fileFields[3].Descriptor()
	// file.DefaultDownloadCount holds the default value on creation for the download_count field.
	file.DefaultDownloadCount = fileDescDownloadCount.Default.(int)
}
