env: "local"
db_host: "localhost"
db_port: "27017"
db_user: ""
db_password: ""
db_name: "cloud-drive"

http_server:
  host: "localhost"
  port: "3001"

rabbitmq:
  user: "guest"
  password: "guest"
  host: "localhost"
  port: "5672"